In [1]:
# import modules/packages
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import KFold, cross_val_score
import matplotlib.pyplot as plt
# import seaborn as sns

In [3]:
# load and clean data
dataset = pd.read_csv('grades_dataset.csv')
print(dataset)

   extra_hours  grade attend_class
0           40   42.6           No
1           40   56.8          Yes
2           60   68.0          Yes
3           70   60.0           No
4           80   69.5           No
5           90   88.1          Yes
6          100   80.4           No
7          110   83.3          Yes
8          120   75.8           No
9          120   94.7          Yes


NameError: name 'sns' is not defined

In [8]:
# prepare datasets to be fed in the model
# predict attend class given extra hours and grade
CV =  dataset.attend_class.values.reshape((len(dataset.attend_class), ))

print(dataset.loc[:,'extra_hours':'grade'].values)
print((len(dataset.attend_class)))
data = (dataset.loc[:,'extra_hours':'grade'].values).reshape((len(dataset.attend_class), 2))

[[ 40.   42.6]
 [ 40.   56.8]
 [ 60.   68. ]
 [ 70.   60. ]
 [ 80.   69.5]
 [ 90.   88.1]
 [100.   80.4]
 [110.   83.3]
 [120.   75.8]
 [120.   94.7]]
10
[[ 40.   42.6]
 [ 40.   56.8]
 [ 60.   68. ]
 [ 70.   60. ]
 [ 80.   69.5]
 [ 90.   88.1]
 [100.   80.4]
 [110.   83.3]
 [120.   75.8]
 [120.   94.7]]


In [5]:
# Create a KNN object
KNN = KNeighborsClassifier(n_neighbors=3)

In [6]:
# Train the model using the training sets
KNN.fit(data, CV)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [7]:
#predict the class for each data point
predicted = KNN.predict(data)
print("Predictions: \n", np.array([predicted]).T)

Predictions: 
 [['Yes']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['Yes']
 ['Yes']]


In [8]:
# predict the probability/likelihood of the prediction
print("Probability of prediction: \n",KNN.predict_proba(data))

Probability of prediction: 
 [[0.33333333 0.66666667]
 [0.33333333 0.66666667]
 [0.66666667 0.33333333]
 [0.66666667 0.33333333]
 [0.66666667 0.33333333]
 [0.33333333 0.66666667]
 [0.33333333 0.66666667]
 [0.66666667 0.33333333]
 [0.33333333 0.66666667]
 [0.33333333 0.66666667]]


In [9]:
print("Neighbors and their Distance: \n",KNN.kneighbors(data, return_distance=True))

Neighbors and their Distance: 
 (array([[ 0.        , 14.2       , 32.32893441],
       [ 0.        , 14.2       , 22.92247805],
       [ 0.        , 12.80624847, 20.05617112],
       [ 0.        , 12.80624847, 13.79311422],
       [ 0.        , 13.79311422, 20.05617112],
       [ 0.        , 12.62101422, 20.56793621],
       [ 0.        , 10.41201229, 12.62101422],
       [ 0.        , 10.41201229, 12.5       ],
       [ 0.        , 12.5       , 18.9       ],
       [ 0.        , 15.16443207, 18.9       ]]), array([[0, 1, 2],
       [1, 0, 2],
       [2, 3, 4],
       [3, 2, 4],
       [4, 3, 2],
       [5, 6, 7],
       [6, 7, 5],
       [7, 6, 8],
       [8, 7, 9],
       [9, 7, 8]]))


In [10]:
print("Accuracy score for the model: \n", KNN.score(data,CV))

Accuracy score for the model: 
 0.5


In [11]:
print(metrics.confusion_matrix(CV, predicted, labels=["Yes","No"]))

[[3 2]
 [3 2]]


In [12]:
# Calculating 5 fold cross validation results
model = KNeighborsClassifier()
kf = KFold(n_splits=5)
scores = cross_val_score(model, data, CV, cv=kf)
print("Accuracy of every fold in 5 fold cross validation: ", abs(scores))
print("Mean of the 5 fold cross-validation: %0.2f" % abs(scores.mean()))

Accuracy of every fold in 5 fold cross validation:  [0.5 0.5 0.5 0.5 0.5]
Mean of the 5 fold cross-validation: 0.50


In [13]:
datapoint = np.array([100,60]).reshape(1, -1)
print("Does he attend class, if he gets 60 after putting 100 hours of effort?\n ",
      KNN.predict(datapoint),'\n' ,KNN.predict_proba(datapoint), '\n' ,KNN.kneighbors(datapoint))

Does he attend class, if he gets 60 after putting 100 hours of effort?
  ['No'] 
 [[0.66666667 0.33333333]] 
 (array([[20.4       , 22.14158983, 25.35527559]]), array([[6, 4, 7]]))


### try different k

In [14]:
KNN_1 = KNeighborsClassifier(n_neighbors=1)
KNN_1.fit(data, CV)
print("Accuracy score for the model:", KNN_1.score(data,CV))
scores = cross_val_score(KNN_1, data, CV, cv=KFold(n_splits=5))
print("Accuracy of every fold in 5 fold cross validation: ", abs(scores))
print("Mean of the 5 fold cross-validation: %0.2f" % abs(scores.mean()))

Accuracy score for the model: 1.0
Accuracy of every fold in 5 fold cross validation:  [0.5 0.5 0.5 0.  0.5]
Mean of the 5 fold cross-validation: 0.40


In [15]:
KNN_2 = KNeighborsClassifier(n_neighbors=2)
KNN_2.fit(data, CV)
print("Accuracy score for the model:", KNN_2.score(data,CV))
scores = cross_val_score(KNN_2, data, CV, cv=KFold(n_splits=5))
print("Accuracy of every fold in 5 fold cross validation: ", abs(scores))
print("Mean of the 5 fold cross-validation: %0.2f" % abs(scores.mean()))

Accuracy score for the model: 0.6
Accuracy of every fold in 5 fold cross validation:  [0.5 0.5 0.5 0.5 0.5]
Mean of the 5 fold cross-validation: 0.50


In [16]:
KNN_4 = KNeighborsClassifier(n_neighbors=4)
KNN_4.fit(data, CV)
print("Accuracy score for the model:", KNN_4.score(data,CV))
scores = cross_val_score(KNN_4, data, CV, cv=KFold(n_splits=5))
print("Accuracy of every fold in 5 fold cross validation: ", abs(scores))
print("Mean of the 5 fold cross-validation: %0.2f" % abs(scores.mean()))

Accuracy score for the model: 0.5
Accuracy of every fold in 5 fold cross validation:  [0.5 0.5 0.5 0.5 0.5]
Mean of the 5 fold cross-validation: 0.50


In [17]:
KNN_10 = KNeighborsClassifier(n_neighbors=6)
KNN_10.fit(data, CV)
print("Accuracy score for the model:", KNN_10.score(data,CV))
scores = cross_val_score(KNN_10, data, CV, cv=KFold(n_splits=5))
print("Accuracy of every fold in 5 fold cross validation: ", abs(scores))
print("Mean of the 5 fold cross-validation: %0.2f" % abs(scores.mean()))

Accuracy score for the model: 0.5
Accuracy of every fold in 5 fold cross validation:  [0.5 0.5 0.5 0.5 0.5]
Mean of the 5 fold cross-validation: 0.50
